const express = require("express");
const router = express.Router();

router.get("/", async (req, res) => {
  const categories = [
    "Technology",
    "Automobiles",
    "Health and Wellness",
    "Travel",
    "Lifestyle",
    "Finance",
    "Parenting",
    "Food and Cooking",
    "Book and Literature",
    "Entertainment",
    "Fitness",
    "Education",
    "Career",
    "Gardening",
    "Sustainability",
    "DIY and Crafts",
    "Pet Care",
    "Science and Nature",
    "Fashion",
    "Beauty",
    "Home Decor",
    "Hobbies",
    "Personal Development",
    "Motivation",
    "Mindfulness",
    "Tech News",
    "Gadgets",
    "Software Development",
    "AI and Machine Learning",
    "Business",
    "Marketing",
    "Social Media",
    "Photography",
    "Art and Design",
    "Music",
    "Home Improvement",
    "Relationships",
    "Weddings",
    "Culinary Arts",
    "Film and Cinema",
    "History",
    "Psychology",
    "Spirituality",
    "Productivity",
    "Self-Care",
    "Travel Photography",
    "Adventure Travel",
    "Cultural Experiences",
    "Fashion Trends",
    "Interior Design",
    "Outdoor Activities",
    "Parenting Hacks",
    "Healthy Recipes",
    "Literary Analysis",
    "Movie Reviews",
    "Technology Trends",
    "Space Exploration",
    "Virtual Reality",
    "Cryptocurrency",
    "Environmental Conservation",
    "Green Living",
  ];

  res.send({
    message: "Category data fetched successfully!",
    categories: categories,
  });
});

module.exports = router;
